version: '3.8'


services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cinncinatus
      - MYSQL_DATABASE=sunshine
    ports:  
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: