version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.35
    
    
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: json-file

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_NAME=$MYSQL_DATABASE
      - MYSQL_PORT=$MYSQL_DOCKER_PORT
    

    command: sh -c "npm install && npm run start:dev"

    develop:
      watch:
        - action: sync
          path: ./src
          target: /myapp/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json