version: "3.8"

services:
  mysqldb:
    image: mysql
    
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: none

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_NAME=$MYSQL_DATABASE
      - MYSQL_PORT=$MYSQL_DOCKER_PORT
    volumes:
      - .:/myapp
    command: sh -c "npm install && npm run start:dev"